---
- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: sathish
      lab: aws
  tasks:
  - name: pring dict variable
    debug:
      msg: "{{ training }}"  
  - name: pring key variables
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value}}"
    with_dict: "{{ training }}"
  - name: pring key1 variable
    debug:
      msg: "{{ training['topic'] }}"
  - name: pring key2 variable
    debug:
      msg: "{{ training.topic }}"
